### ISSUE TITLE
Packer download location has changed

### ISSUE THREAD

**Issue by znorris** [GoogleCloudPlatform/jenkins-packer-agent#5]
The packer link should now be:
`https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip`

I'll submit a PR later today or tomorrow when I have a minute.

**Comment by evandbrown** [comment]
Awesome, thanks! When you submit the PR, will you also please sign the [Google CLA](https://cla.developers.google.com/) so I can merge it?

**Comment by znorris** [comment]
:+1:
